### ISSUE TITLE
Valid expression of form ... <function-call() highlights an issue

### ISSUE THREAD

**Issue by ligasgr** [rhdunn/xquery-intellij-plugin#45] opened 2017-01-21 22:15 UTC
With expression like this one:
```xquery
1 <fn:abs(1)
```
I'm getting errors highlighted:
```
1 <fn:abs(1)
  ^      ^^^
  |     XPST0003: Expected '>', '/>' or attribute name.
XPST0003: Expected end of file.
```

**Comment by rhdunn** [comment] 2017-01-21 22:50
That is the expected behaviour according to the XQuery grammar. https://www.w3.org/TR/xquery-30/#prod-xquery30-DirElemConstructor is marked as ws:explicit and does not have any whitespace between "<" and QName, so the construct is invalid without whitespace after the `<`. Saxon generates a similar error for that construct.

The `XPST0003: Expected end of file.` message is because you have an IntegererLiteral followed by a DirElemConstructor (i.e. two expressions without anything connecting them).

The parser is then using error recovery to continue parsing, so it attempts to parse the DirElemConstructor. This is why you get the `XPST0003: Expected '>', '/>' or attribute name.` error.

Are you aware of any implementations that work with your example query?

**Comment by ligasgr** [comment] 2017-01-21 22:55
Yes, Saxon 9.7 runs this without any issues.

**Comment by ligasgr** [comment] 2017-01-21 22:56
Also tried with baseX in embedded mode. Works without any issues as this is valid syntax.

**Comment by rhdunn** [comment] 2017-02-06 13:28
This has now been fixed. Thanks for the bug report.

**Closed by rhdunn** 2017-02-06 13:28 UTC
Labels: bug
